package com.asynclife.swing.showpdf;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;

public class CustomImgPanel extends javax.swing.JPanel {


    private int width = 0;
    private int height = 0;
    Image image;


    /**
     *
     * @param _width 整型,窗口的宽度
     * @param _height 整型,窗口的高度
     * @param _imgPath 图片的URL,可用相对路径
     */
    public CustomImgPanel(int _width, int _height, Image _image) {
        width = _width;
        height = _height;
        image = _image;
        setSize(width, height);
        setVisible(true);
    }


    /**
     *
     * @param _width 浮点型,窗口的宽度
     * @param _height 浮点型,窗口的高度
     * @param _imgPath 字符串,图片的URL,可用相对
     */
    public CustomImgPanel(double _width, double _height, Image _image) {
        width = (int) _width;
        height = (int) _height;
        image = _image;
        setSize(width, height);
        setVisible(true);
    }


    @Override
    public void paintComponent(Graphics gs) {
        Graphics2D g = (Graphics2D) gs;
        super.paintComponent(g);
        g.drawImage(image, 0, 0, width, height, this);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        
    // Variables declaration - do not modify                     
    // End of variables declaration                   
}

