/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '16-4-23 下午10:25' with Gradle 2.12
 *
 * @author Administrator, @date 16-4-23 下午10:25
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
