server:
    port: 80
    context-path: /web

application:
    message: Hello Alice
    
spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
        static-path-pattern: /static/**

      
   
